### ISSUE TITLE
MQTT library not included in mos.yml

### ISSUE THREAD

**Issue by fabiohmantelli** [mongoose-os-libs/mjs#17]
Even though MQTT functions are called in the mongoose-os-libs/mjs/fs/init.js file (which gets put in the device's file system), the api_mqtt.js repository is not included in the mos.yml file.

This should not be a problem if someone writes it's own fs/init.js file because in this case, the mjs init.js file gets overwritten by the users init.js file.

I noticed this when adding the mjs library without any fs/init.js file. I flashed my firmware and got a `MJS error: failed to exec file "api_mqtt.js": failed to read file "api_mqtt.js"`

Either the MQTT code in mongoose-os-libs/mjs/fs/init.js file must be removed or changed to only include already loaded libraries (I think this is the best option), or the MQTT library should be added in the mos.yml file.

Thanks

**Comment by rojer** [comment]
yes, you are right. in fact, mjs library should not ship any init.js with it, it should be left up to the app.

**Comment by rojer** [comment]
done
