### ISSUE TITLE
Sys.reboot(us) no longer receive arguments

### ISSUE THREAD

**Issue by bemomos** [mongoose-os-libs/mjs#7]
API documentation states that Sys.reboot(us) receives us as argument time delay reboot. In the source code is clear that the FFI'ed function receive no arguments (void), so if Sys.reboot is called with arguments, the call fail:
MJS callback error: failed to call FFIed function: got 1 actuals, but function takes 0 args

**Comment by rojer** [comment]
hm, i see. mgos_system_restart used to take an int argument but no longer does.
actually, even when it did, this didn't work like that - the int argument was "exit code", which made no sense and was removed.
i'm going to take a n opportunity to fix this properly. note that i'm also changing argument to milliseconds.
